/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

public class App {

    public static void main(String[] args) {

//        ProjectController projectController = new ProjectController();

//        Project project = new Project();
//        project.setId(4);
//        project.setName("Test Project Four(4)");
//        project.setDescription("Fourth Test Project(4)");
//        projectController.update(project);
        
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos: " + projects.size());
//        System.out.println(projects);
//        projectController.removeById(4);
        
//        TaskController taskController = new TaskController();
        
//        Task task = new Task();
//        task.setId(3);
//        task.setIdProject(1);
//        task.setName("Task Four");
//        task.setDescription("Fourth task Project One");
//        task.setNotes("Fourth task Project One");
//        task.setIsCompleted(false);
//        taskController.save(task);
//        taskController.update(task);

//        taskController.removeById(4);
//        
//        List<Task> tasks = taskController.getAll(1);
//        System.out.println("Total de tarefas do projeto: " + tasks.size());
//        System.out.println(tasks);
    }
}
